//
//  TestJson.swift
//  GayhubSwiftify
//
//  Created by 王籽涵 on 2020/8/20.
//  Copyright © 2020 hahn. All rights reserved.
//

let testJson =
"""
[
    {
        "id": 109653792,
        "node_id": "MDEwOlJlcG9zaXRvcnkxMDk2NTM3OTI=",
        "name": "awesome",
        "full_name": "WhatTheNathan/awesome",
        "private": false,
        "owner": {
            "login": "WhatTheNathan",
            "id": 22427632,
            "node_id": "MDQ6VXNlcjIyNDI3NjMy",
            "avatar_url": "https://avatars3.githubusercontent.com/u/22427632?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/WhatTheNathan",
            "html_url": "https://github.com/WhatTheNathan",
            "followers_url": "https://api.github.com/users/WhatTheNathan/followers",
            "following_url": "https://api.github.com/users/WhatTheNathan/following{/other_user}",
            "gists_url": "https://api.github.com/users/WhatTheNathan/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/WhatTheNathan/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/WhatTheNathan/subscriptions",
            "organizations_url": "https://api.github.com/users/WhatTheNathan/orgs",
            "repos_url": "https://api.github.com/users/WhatTheNathan/repos",
            "events_url": "https://api.github.com/users/WhatTheNathan/events{/privacy}",
            "received_events_url": "https://api.github.com/users/WhatTheNathan/received_events",
            "type": "User",
            "site_admin": false
        },
        "html_url": "https://github.com/WhatTheNathan/awesome",
        "description": ":sunglasses: Curated list of awesome lists",
        "fork": true,
        "url": "https://api.github.com/repos/WhatTheNathan/awesome",
        "forks_url": "https://api.github.com/repos/WhatTheNathan/awesome/forks",
        "keys_url": "https://api.github.com/repos/WhatTheNathan/awesome/keys{/key_id}",
        "collaborators_url": "https://api.github.com/repos/WhatTheNathan/awesome/collaborators{/collaborator}",
        "teams_url": "https://api.github.com/repos/WhatTheNathan/awesome/teams",
        "hooks_url": "https://api.github.com/repos/WhatTheNathan/awesome/hooks",
        "issue_events_url": "https://api.github.com/repos/WhatTheNathan/awesome/issues/events{/number}",
        "events_url": "https://api.github.com/repos/WhatTheNathan/awesome/events",
        "assignees_url": "https://api.github.com/repos/WhatTheNathan/awesome/assignees{/user}",
        "branches_url": "https://api.github.com/repos/WhatTheNathan/awesome/branches{/branch}",
        "tags_url": "https://api.github.com/repos/WhatTheNathan/awesome/tags",
        "blobs_url": "https://api.github.com/repos/WhatTheNathan/awesome/git/blobs{/sha}",
        "git_tags_url": "https://api.github.com/repos/WhatTheNathan/awesome/git/tags{/sha}",
        "git_refs_url": "https://api.github.com/repos/WhatTheNathan/awesome/git/refs{/sha}",
        "trees_url": "https://api.github.com/repos/WhatTheNathan/awesome/git/trees{/sha}",
        "statuses_url": "https://api.github.com/repos/WhatTheNathan/awesome/statuses/{sha}",
        "languages_url": "https://api.github.com/repos/WhatTheNathan/awesome/languages",
        "stargazers_url": "https://api.github.com/repos/WhatTheNathan/awesome/stargazers",
        "contributors_url": "https://api.github.com/repos/WhatTheNathan/awesome/contributors",
        "subscribers_url": "https://api.github.com/repos/WhatTheNathan/awesome/subscribers",
        "subscription_url": "https://api.github.com/repos/WhatTheNathan/awesome/subscription",
        "commits_url": "https://api.github.com/repos/WhatTheNathan/awesome/commits{/sha}",
        "git_commits_url": "https://api.github.com/repos/WhatTheNathan/awesome/git/commits{/sha}",
        "comments_url": "https://api.github.com/repos/WhatTheNathan/awesome/comments{/number}",
        "issue_comment_url": "https://api.github.com/repos/WhatTheNathan/awesome/issues/comments{/number}",
        "contents_url": "https://api.github.com/repos/WhatTheNathan/awesome/contents/{+path}",
        "compare_url": "https://api.github.com/repos/WhatTheNathan/awesome/compare/{base}...{head}",
        "merges_url": "https://api.github.com/repos/WhatTheNathan/awesome/merges",
        "archive_url": "https://api.github.com/repos/WhatTheNathan/awesome/{archive_format}{/ref}",
        "downloads_url": "https://api.github.com/repos/WhatTheNathan/awesome/downloads",
        "issues_url": "https://api.github.com/repos/WhatTheNathan/awesome/issues{/number}",
        "pulls_url": "https://api.github.com/repos/WhatTheNathan/awesome/pulls{/number}",
        "milestones_url": "https://api.github.com/repos/WhatTheNathan/awesome/milestones{/number}",
        "notifications_url": "https://api.github.com/repos/WhatTheNathan/awesome/notifications{?since,all,participating}",
        "labels_url": "https://api.github.com/repos/WhatTheNathan/awesome/labels{/name}",
        "releases_url": "https://api.github.com/repos/WhatTheNathan/awesome/releases{/id}",
        "deployments_url": "https://api.github.com/repos/WhatTheNathan/awesome/deployments",
        "created_at": "2017-11-06T05:58:30Z",
        "updated_at": "2017-11-06T05:58:17Z",
        "pushed_at": "2017-11-04T11:56:05Z",
        "git_url": "git://github.com/WhatTheNathan/awesome.git",
        "ssh_url": "git@github.com:WhatTheNathan/awesome.git",
        "clone_url": "https://github.com/WhatTheNathan/awesome.git",
        "svn_url": "https://github.com/WhatTheNathan/awesome",
        "homepage": "",
        "size": 683,
        "stargazers_count": 0,
        "watchers_count": 0,
        "language": null,
        "has_issues": false,
        "has_projects": true,
        "has_downloads": true,
        "has_wiki": true,
        "has_pages": false,
        "forks_count": 0,
        "mirror_url": null,
        "archived": false,
        "disabled": false,
        "open_issues_count": 0,
        "license": null,
        "forks": 0,
        "open_issues": 0,
        "watchers": 0,
        "default_branch": "master"
    }
]
"""
